export const ROUTES = {
    // login / registration
    ROOT: "/",
    LOGIN: "/login",
    SIGNUP: "/signup",
    SIGNUP_PROVISIONAL: "/signup-provisional",
    SIGNUP_COMPLETED: "/signup-completed",
    RESET_MAIL_COMPLETED: "/reset-email-completed",
    RECOVER_MAIL_COMPLETED: "/recover-email-completed",
    RESET_PASSWORD: "/reset-password",
    RESET_PASSWORD_SENT: "/reset-password-sent",
    RESET_PASSWORD_INPUT: "/reset-password-input",
    RESET_PASSWORD_COMPLETE: "/reset-password-complete",
    REVERT_SECOND_FACTOR_ADDITION: "/revert-second-factor-addition",
    ACCOUNT_DELETED: "/account-deleted",
    ERROR: "/error",
    ACCOUNT_ACTION: "/account-action",
    CHANGE_PLAN: "/change-to-free-plan",
    PROJECTS_NOT_FOUND: "/projects-not-found",
    PROJECT_NOT_FOUND_ERROR: "/project-not-found-error",
    PROJECTS: "/projects",

    // dashboard
    APPLICATIONS: "/applications",
    APPLICATIONS_DETAIL: "/applications/detail",
    APPLICATIONS_DETAIL_ANALYTICS: "/applications/detail/analytics",
    APPLICATIONS_DETAIL_ANALYTICS_CHANNEL: "/applications/detail/analytics/channel",
    APPLICATIONS_DETAIL_ANALYTICS_CHANNEL_MEMBERS: "/applications/detail/analytics/channel/members",
    APPLICATIONS_DETAIL_ANALYTICS_CHANNEL_MEMBERS_PUBSUBSTATS:
        "/applications/detail/analytics/channel/members/pubsubstats",
    APPLICATIONS_NEW: "/applications/new",
    APPLICATIONS_RECORDING: "/recording",
    APPLICATIONS_BROADCAST: "/broadcast",
    APPLICATIONS_NOTIFICATION: "/notification",
    APPLICATIONS_SECURITY: "/security",
    APPLICATIONS_ANALYTICS: "/analytics",

    ACCOUNT: "/account",
    ACCOUNT_RESET_MAIL: "/account/reset-email",
    ACCOUNT_PLAN: "/change-to-enterprise-plan",
    ACCOUNT_PAYMENT: "/payment",
    INVITE_TOP: "/invite",
    INVITE_SIGNUP: "/invite-signup",
    INVITE_SIGNUP_COMPLETED: "/invite-signup-completed",
    INVITE_LOGIN: "/invite-login",
    INVITE_RESET_PASSWORD: "/invite-reset-password",
    INVITE_RESET_PASSWORD_SENT: "/invite-reset-password-sent",
    USAGE: "/usage",
    PROJECTS_DETAIL: "/project-detail",
} as const;
